### ISSUE TITLE
20250220 오피스아워 질문

### ISSUE THREAD

**Issue by jiwon2030** [TeamAssign/Assign-backend#14]
In GitLab by @BugeonJo on Feb 20, 2025, 10:56 GMT+9

1. 후기에서 유저들이 메뉴 이름을 적을건데 음식 테이블에 존재하지 않는 음식 이름을 말하거나 잘못된 이름을 작성하는 경우의 대응 방안을 고민중입니다. 지금은 ai를 돌려서 validation 체크 후 잘못된 경우 ai가 교정해주는 방안을 고민 중입니다.
(예시: 빅맥 -> 햄버거,  맛있는 똠양꿍 -> 똠양꿍)

2. 저희 팀이 아직 로그 처리를 안하고 있는데 보통 어떻게 처리하는지 궁금합니다. 특히 지금은 NoSql을 사용하고 있기 때문에 더 로그를 작성하는 것이 해봄직하지 않나 싶은데, 일반적인 처리 방법 혹은 좋은 라이브러리가 있는지 궁금합니다. Aop를 사용하는지 등

3. GlobalExceptionHandler 실무에서 에러 처리 어떻게 하는지 궁금합니다. 지금은 이렇게 하고 있습니다.
```java
public class GlobalExceptionHandler {

    /**
     * CustomException 예외 처리
     */
    @ExceptionHandler(CustomException.class)
    public ResponseEntity<ErrorResponse> handleCustomException(CustomException ex) {
        return ResponseEntity
                .status(ex.getErrorCode().getStatus())
                .body(ErrorResponse.of(ex.getErrorCode()));
    }

    /**
     * 유효성 검증 예외 처리
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handleValidationException(MethodArgumentNotValidException ex) {
        return ResponseEntity
                .status(ErrorCode.VALIDATION_ERROR.getStatus())
                .body(new ErrorResponse(ex.getClass().getSimpleName(), ex.getMessage()));
    }

    /**
     * 예상하지 못한 예외 처리
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleGlobalException(Exception ex) {
        return ResponseEntity
                .status(ErrorCode.INTERNAL_SERVER_ERROR.getStatus())
                .body(ErrorResponse.of(ErrorCode.INTERNAL_SERVER_ERROR));
    }
}

```

4. jpa 양방향, 단방향 중 뭘 선호하시는지 궁금하고, 연결 테이블 복합키 사용하시는지 고유키 사용하시는지 궁금합니다.

5. 혹시 로컬로 돌릴만한 이미지 생성 ai 좋은 게 있을까요? 그리고 돌릴 때 어떻게 돌릴지 궁금합니다.(M4 프로 유저)

6. 코드 리뷰 시간 조정이 좀 가능할까요?

7. DockerFile과 docker-compose파일 제대로 만들었는지 궁금합니다.

```
FROM openjdk:17-slim AS builder
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew build -x test

FROM openjdk:17-slim
WORKDIR /app
COPY --from=builder /app/build/libs/*SNAPSHOT.jar app.jar
CMD java -jar app.jar

version: "3"
services:
  assign:
    container_name: assign_BE
    build:
      context: ./spring/assign-back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pgvectorDB

  pgvectorDB:
    container_name: pgvectorDB
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: assign
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped


```

*Migrated from GitLab: https://kdt-gitlab.elice.io/pttrack/class_01/web_project_ii/team03/assgin-back/-/issues/14*
